// User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';

// UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
// Data reducer types
export const SET_PRODUITS = 'SET_PRODUITS';
export const SET_PRODUIT = 'SET_PRODUIT';
export const LIKE_PRODUIT = 'LIKE_PRODUIT';
export const UNLIKE_PRODUIT = 'UNLIKE_PRODUIT';
export const DELETE_PRODUIT = 'DELETE_PRODUIT';
export const POST_PRODUIT = 'POST_PRODUIT';
export const UPDATE_PRODUITS = 'UPDATE_PRODUITS';
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';
export const GET_COMMENT_PRODUCTS = 'GET_COMMENT_PRODUCTS';
export const GET_COMMENT_TO_CURRENT_LISTES_PRODUCTS= 'GET_COMMENT_TO_CURRENT_LISTES_PRODUCTS'
export const LOAD_IMAGE_DATA_TO_REUSE= 'LOAD_IMAGE_DATA_TO_REUSE'
export const LOAD_IMAGE_DATA_TO_REUSEONE= 'LOAD_IMAGE_DATA_TO_REUSEONE'
export const LOAD_IMAGE_DATA_TO_REUSETWO= 'LOAD_IMAGE_DATA_TO_REUSETWO'
export const LOAD_IMAGE_DATA_TO_REUSETHREE= 'LOAD_IMAGE_DATA_TO_REUSETHREE'
